# This workflow handles continuos integration

name: Unit Tests

# When
on:
  # On push or pull request events on the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# Jobs
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.6]

    # Steps
    steps:
    - name: Git checkout 
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Create .env file
      run: echo ${{ secrets.BASE_URL }} > .env

    - name: Run Unit test
      run: |
        cd src && pytest
